name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Github Repository
        uses: actions/checkout@v4

      - name: install jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: create application.yml
        run: echo "${{ secrets.APPLICATION_MAIN_PROPERTIES }}"
      - name: create application-aws.yml
        run: echo "${{ secrets.APPLICATION_MAIN_AWS_PROPERTIES }}"
      - name: create application-test.yml
        run: echo "${{ secrets.APPLICATION_TEST_PROPERTIES }}"
      - name: create application-test-aws.yml
        run: echo "${{ secrets.APPLICATION_TEST_AWS_PROPERTIES }}"

