name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_MAIN_PROPERTIES: ${{ secrets.APPLICATION_MAIN_PROPERTIES }}
          APPLICATION_MAIN_AWS_PROPERTIES: ${{ secrets.APPLICATION_MAIN_AWS_PROPERTIES }}
          APPLICATION_TEST_PROPERTIES: ${{ secrets.APPLICATION_TEST_PROPERTIES }}
          APPLICATION_TEST_AWS_PROPERTIES: ${{ secrets.APPLICATION_TEST_AWS_PROPERTIES }}

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/server # 여기 경로는 자신의 EC2에 맞는 경로로 재작성하기
            rm -rf src/main/resources/application.yml
            rm -rf src/main/resources/application-aws.yml
            rm -rf src/test/resources/application.yml
            rm -rf src/test/resources/application-test.yml
            git pull origin main
            echo "$APPLICATION_MAIN_PROPERTIES" > src/main/resources/application.yml
            echo "$APPLICATION_MAIN_AWS_PROPERTIES" > src/main/resources/application-aws.yml
            echo "$APPLICATION_TEST_PROPERTIES" > src/test/resources/application.yml
            echo "$APPLICATION_TEST_AWS_PROPERTIES" > src/test/resources/application-test.yml
            chmod +x ./gradlew
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true # || true 
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
            
