name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/server # 여기 경로는 자신의 EC2에 맞는 경로로 재작성하기
            rm -rf src/main/resources/application.yml
            rm -rf src/main/resources/application-aws.yml
            rm -rf src/test/resources/application.yml
            rm -rf src/test/resources/application-test.yml
            git pull origin main
            echo "${{ secrets.APPLICATION_MAIN_PROPERTIES }}" > src/main/resources/application.yml
            echo "${{ secrets.APPLICATION_MAIN_AWS_PROPERTIES }}" > src/main/resources/application-aws.yml
            echo "${{ secrets.APPLICATION_TEST_PROPERTIES }}" > src/test/resources/application.yml
            echo "${{ secrets.APPLICATION_TEST_AWS_PROPERTIES }}" > src/test/resources/application-test.yml
#              chmod +x ./gradlew
#              ./gradlew clean build -x test
#              sudo fuser -k -n tcp 80 || true # || true
#              nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
            
